# Generated by Django 4.2.5 on 2025-11-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
